defmodule Data do
    def day1 do
        9513446799636685297929646689682997114316733445451534532351778534251427172168183621874641711534917291674333857423799375512628489423332297538215855176592633692631974822259161766238385922277893623911332569448978771948316155868781496698895492971356383996932885518732997624253678694279666572149831616312497994856288871586777793459926952491318336997159553714584541897294117487641872629796825583725975692264125865827534677223541484795877371955124463989228886498682421539667224963783616245646832154384756663251487668681425754536722827563651327524674183443696227523828832466473538347472991998913211857749878157579176457395375632995576569388455888156465451723693767887681392547189273391948632726499868313747261828186732986628365773728583387184112323696592536446536231376615949825166773536471531487969852535699774113163667286537193767515119362865141925612849443983484245268194842563154567638354645735331855896155142741664246715666899824364722914296492444672653852387389477634257768229772399416521198625393426443499223611843766134883441223328256883497423324753229392393974622181429913535973327323952241674979677481518733692544535323219895684629719868384266425386835539719237716339198485163916562434854579365958111931354576991558771236977242668756782139961638347251644828724786827751748399123668854393894787851872256667336215726674348886747128237416273154988619267824361227888751562445622387695218161341884756795223464751862965655559143779425283154533252573949165492138175581615176611845489857169132936848668646319955661492488428427435269169173654812114842568381636982389224236455633316898178163297452453296667661849622174541778669494388167451186352488555379581934999276412919598411422973399319799937518713422398874326665375216437246445791623283898584648278989674418242112957668397484671119761553847275799873495363759266296477844157237423239163559391553961176475377151369399646747881452252547741718734949967752564774161341784833521492494243662658471121369649641815562327698395293573991648351369767162642763475561544795982183714447737149239846151871434656618825566387329765118727515699213962477996399781652131918996434125559698427945714572488376342126989157872118279163127742349
    end

    def day2 do
    [[1136,1129,184,452,788,1215,355,1109,224,1358,1278,176,1302,186,128,1148],
    [242,53,252,62,40,55,265,283,38,157,259,226,322,48,324,299],
    [2330,448,268,2703,1695,2010,3930,3923,179,3607,217,3632,1252,231,286,3689],
    [89,92,903,156,924,364,80,992,599,998,751,827,110,969,979,734],
    [100,304,797,81,249,1050,90,127,675,1038,154,715,79,1116,723,990],
    [1377,353,3635,99,118,1030,3186,3385,1921,2821,492,3082,2295,139,125,2819],
    [3102,213,2462,116,701,2985,265,165,248,680,3147,1362,1026,1447,106,2769],
    [5294,295,6266,3966,2549,701,2581,6418,5617,292,5835,209,2109,3211,241,5753],
    [158,955,995,51,89,875,38,793,969,63,440,202,245,58,965,74],
    [62,47,1268,553,45,60,650,1247,1140,776,1286,200,604,399,42,572],
    [267,395,171,261,79,66,428,371,257,284,65,25,374,70,389,51],
    [3162,3236,1598,4680,2258,563,1389,3313,501,230,195,4107,224,225,4242,4581],
    [807,918,51,1055,732,518,826,806,58,394,632,36,53,119,667,60],
    [839,253,1680,108,349,1603,1724,172,140,167,181,38,1758,1577,748,1011],
    [1165,1251,702,282,1178,834,211,1298,382,1339,67,914,1273,76,81,71],
    [6151,5857,4865,437,6210,237,37,410,544,214,233,6532,2114,207,5643,6852]]
    end
    def day4 do
        ["kvvfl kvvfl olud wjqsqa olud frc",
        "slhm rdfm yxb rsobyt rdfm",
        "pib wzfr xyoakcu zoapeze rtdxt rikc jyeps wdyo hawr xyoakcu hawr",
        "ismtq qwoi kzt ktgzoc gnxblp dzfayil ftfx asscba ionxi dzfayil qwoi",
        "dzuhys kfekxe nvdhdtj hzusdy xzhehgc dhtvdnj oxwlvef",
        "gxg qahl aaipx tkmckn hcsuhy jsudcmy kcefhpn kiasaj tkmckn",
        "roan kqnztj edc zpjwb",
        "yzc roc qrygby rsvts nyijgwr xnpqz",
        "jqgj hhgtw tmychia whkm vvxoq tfbzpe ska ldjmvmo",
        "nyeeg omn geyen ngyee rcjt rjuxh",
        "qpq udci tnp fdfk kffd eyzvmg ufppf wfuodj toamfn tkze jzsb",
        "rrcgxyp rbufd tfjmok vpyhej hcnz ftkojm",
        "jnmomfc jnmomfc bkluz izn ovvm flsch bkluz",
        "odisl hzwv hiasrhi hez ihihsra qpbmi ltwjj iknkwxf nbdtq gbo",
        "gjtszl gjtszl fruo fruo",
        "rdapv gaik cqboix sxnizhh uxmpali jdd usqnz advrp dze",
        "flooz flooz qad tcrq yze bnoijff qpqu vup hyagwll",
        "lnazok dze foi tqwjsk hpx qcql euzpj mwfrk",
        "ilb fmviby ivybmf gtx xtg",
        "rpauuu timere gyg wcolt ireetm safi",
        "croe szwmq bbhd lciird vhcci pdax",
        "hnc ykswt qqqmei goe bri wmyai hnc qpgqc pberqf bzs",
        "hsnrb wdvh iezzrq iezzrq rdbmpta iezzrq kemnptg alkjnp wymmz",
        "ngw don ddvyds nlhkoa aaf gptumum ugtpmmu",
        "vmccke qbpag kvf kvf tgrfghb kvf bhpd sglgx",
        "obomgk bkcgo yso ttft vbw ckl wjgk",
        "fli qvw zhin dfpgfjb udsin nihz ovr tiewo",
        "tgmzmph hauzieo jmg tdbtl lvfr qpaayq qapaqy ausioeu jun piygx",
        "jkp guqrnx asdqmxf vmfvtqb tloqgyo ioix gajowri tmek ilc puhipb",
        "uycn zxqm znft ayal znacus kvcyd ekv qqfpnh",
        "fqghur xtbtdd ztjrylr bpuikb ziyk",
        "rvakn uqbl ozitpdh uqbl dsej xehj",
        "laxp haz jyd xnkrb ijldth woy xapl iqgg alpx gnupa ukptmmh",
        "dyiy dyiy ihb qcyxr",
        "wbwkd hdwu zvgkn hdwu wjc sakwhn zxujdo npllzp uyr uyr",
        "fxczpmn cininu akcxs ggslxr riyxe ojisxe",
        "ppbch sampq dnct afikor dnct edsqy pnzyzmc afikor",
        "jnvygtn hijqjxl vsd jnvygtn nqcqv zns odq gkboxrv kolnq wrvd",
        "mroq mroq flsbu flsbu",
        "fyshor xvpaunj qmktlo xoce wkiyfu ukcl srndc ugwylwm ozcwdw mtqcste kpokr",
        "cfh cxjvx cfh cfh uewshh",
        "bpspbap bpspbap fquj mxmn bwls iirhvuk dmpkyt exrn mxmn",
        "tvyvzk ezszod ntxr xtnr och",
        "knfxhy kbnyl knfxhy xhkssx lxru uprh nkxpbx oodolxr tpvyf",
        "nblmysu iwoffs upgof tyagwf aan vovji ajk ywzq oyfi sfulz",
        "aushzkm lcaeki mkuzsah ynxvte rsntd refk pcm",
        "mgguob gobmug dzenpty gmogbu",
        "yvq eepof rgnree nerger fpb stfrln ernger",
        "hrgkbl mzwvswk rsrsbk ieru holco pajvvn ztgsr qkyp fyeg owpcmoj",
        "fowda gmsqdca yugj mcrroxv mqcbojd fjnqfji qdfsc jqs",
        "qnc rvjfz vvxk sjd xrma ucdjvq sbw zydyt dfzww",
        "ocajazv cozaajv tqunkla udwf ecnnmbz lsakqg bki njnda zsdu ccfqw rxpc",
        "qqm qdfya qxyx qmq qfday uqnfttt",
        "rnbirb iapor qet iapor hxkhz dfvzig pedl ybyb",
        "mkgamxg xkniv meb hbzmxjn dhbj zhbxjmn hdjb",
        "ilteux pyutyfx mau lrr bacak",
        "sjjonmn dbbbgs crxyuu jztstgd ezb uiabyaa",
        "tra fle ufzlvf nnaw kec hiwnnlj tei wld iyt syk hjdczb",
        "qmd jtlud dgh dbanock fzp dsjgqru wwvo jwvxwgv xlemfij jcacd",
        "rpkx oxesil snazcgx fly miiyc ikmtmp oefyyn egbw",
        "ypfpeu wldnyd acchppb yqwcaw wldnyd turbz megci nbgxq xkc ypfpeu",
        "iqqv iqqv neui iqqv",
        "ypsxm icqyup zyetrwq nbisrv",
        "viommi toszx dpueq eyy cunjou ffcjc jaeez djefra pxvkj liudlig yye",
        "fhnacbg jghchh ghjhhc iue hwqmo",
        "vbjw lpn cizba ltnsfpz tzoweml irewlc uzckhpd mszal obd",
        "yeos utxkft hflxkfe fxczge qpgigkc ksgr vuumql vhlvv",
        "xzmkv xzmkv krecdi klpem jsbu nwcmik emfzxf cjmpgnj",
        "vtkjo pmiv zou gxo qdiyxsf hwyinjk jhkgf rjq",
        "dyuoc ywiyvch irfgl ywiyvch fxb fxb",
        "tuz onhr syu rqya abkaf bcfx mbknex juwoor zmksl",
        "oheg spjorx ksdy vwtq fxz phvtazk tcze lrxg",
        "hew lbup botaj ltr jpd",
        "dxgc tzinkej gnz hxvvub adsqmc dxgc asgpp rqbdcra goy pmamdua bhiacva",
        "xqv ygb kihxqz vyv pjcny vmyvsdv cgsi nfyx",
        "tqga ssshrw ndq qlbvwh huyd pxbgj qbxk dkkbf jxy chsobw pph",
        "hxl iwph iwph xnr otifm ljhre",
        "zlgvpd kapxpoc dve rklk ogh hgnp rbrmc zzkz hhmcx aklmo",
        "sar gfor nkf hek nkf aql shc aql",
        "dtcrw kfjzcjx qyhi bldson whwdayo mqtgt xhqzp ttqmg",
        "omspdml isze jdl nvwo qrkm wztfg ssfgyh dryj jhp unsmty",
        "jxt cszylng ifht ixtuna azoi xutqlv jtx tjx",
        "usgm azuayp fgkby ezpyq jqwl ezofj",
        "tnhvil nrvg moyrpqs sldx qymoff megflxh pyhqwms xmdw",
        "zomy zcquwnv lzx bvcna yods mjp dgsez",
        "blklyf xokd gpit tiysj yrwfhm tofx",
        "dtig vhdp omuj vhpd",
        "fogwxim qvdwig emdiv jvhl euwbzkg xvxb hwmqo ujdmlp epmykj",
        "sjxll sjxll pedvgb sjxll",
        "drvay gtzhgtx yrt okz nqf",
        "haxfazn pvkovwb pgu tgshw mxcjf pbe nwoymzc mxcjf pbe hydwy jradcr",
        "prjsloa ahylvj okbsj qbdcdjt pmfo pagyoeg vkmhjzt khzmjvt opfm xfrji gyjqyel",
        "lzypt jdbtrad ogr jdbtrad heink",
        "rcoucuq gdxewa rcoucuq whlw zhhm rcoucuq azaqohe mzyli rdvaf",
        "yuag ebcf yuag nsotg qqzuxr jfmao vyucw wmoye",
        "qwvk xemm hgqrr wyxkpp tojndm xlvzypw jus bgnu bgnu nklfwhs",
        "daqi knenmku ccm xkiuy vkexsbc kvvdagx umopitw yaocnx yoakqql mllmsp",
        "mrxgl gywit mfopia ncnsvw vdxek axuiot rsejua nei prndudz mnu",
        "egqn gaa qgen urs mix zbn rhn",
        "ewharq aihy udkdaob kgrdd kgrdd kugbjtj fcef llqb pduxaq wcexmm",
        "dwtiw nelq hppad algxgf gcc upou akm efnb mxmhrud",
        "yxqaa ups okbhgt iet qns tqn rnjqxgp",
        "npmhdm cgds ldexvr typi jyivoqk zkgq vfyxu xgfo",
        "dkwnmr umm dkwnmr okpjw wqx jpztebl eqsib dkwnmr",
        "dxbild wpbup evscivq dxbild dxbild geqp ojfbpl jshvqej",
        "cxdntxs csfocjd pyy tuhws teb boyloz xfw scxh pxhonky",
        "lteucke xrgwy hszgzu hnyrcvb",
        "pfgsgwg dxzh fworek qbstod",
        "usemcrf psczxu gcjtr brls",
        "hjol efxczux bqdn gvrnpey yyoqse gbam ndzyj lbwb bhzn unsezg",
        "bapw xifz blupk qqdk bofvqpp wnbuwyt rnwocu lzwgtt zucag pov",
        "xkre lqvd juf lqvd xio xyg xyg",
        "tzdao ztheib aymcf aorg iyawrch hetcxa iyawrch czdymc ccv",
        "ucgl azlppu jvxqlj pest",
        "dvwlw fuuy mnhmm okrp ualnqlm uyuznba fzyejk yaq crl ctprp",
        "odfq knox mkbcku pxucmuf lpjpol phl",
        "ixongh hfs ruorbd auy qyssl kykwcix aytsm rlj aytsm duq segpqhk",
        "izufsk wedpzh podjkor eamo vqvev ifnz podjkor xrnuqe",
        "twyfps bmdbgtu qye qkwjms",
        "wlav htym vhsnu cocphsj mdsuq vhsnu jflgmrp",
        "opajag itwjhfu purnnvk opajag",
        "hpkopqp vnj aialpt lzrkzfs nwucez nwuezc",
        "mcx hzcjxq zbxr dsx tpknx fva",
        "rlvgm xrejsvn ghawxb efyos xty wdzdgh olahbtn rga efyos vhtm nsr",
        "cni mbab qtgeiow ulttn rckc kmiaju jvbq emyvpew cdlxldn ulttn brhkprx",
        "eykpffp rapik qki fhjgdyu tome ehjuy bibjk htxd vexvag",
        "wrk dpxt gwkuiov gbkif ike gbkif pcd wpj toywyf qzsa aol",
        "yqwzh uujn ujun ujnu",
        "srs ralwxrz yxvvmgp sjhbhk waasid cqtxoxf whcladv jkmaq khjbsh dlavcwh",
        "mdvsjh xaj etvxlsy fxgiy rgjesel rlegesj ptriz ebdyhkp kugxm dxv egljser",
        "lhehwrs mqevb ygmv gri izop qgb ivm",
        "loqqam alojlwg hgen hbyw qlwpun loqqam worgnwk kope",
        "phozre todsknr todsknr ibj mvllsar",
        "wuripy ruwlfbh wukbkey qhq iishw tvtvci xawvxc vxacwx hsiwi ogq",
        "xryq vxwupqa zhqex aquxpwv bnvxrba dtbxki",
        "yvvwh zvsm vqskhp vqskhp ggqqlw bpn wbuv",
        "kqz tdy goqwge ygn jgd",
        "szjjhdk zkpoo nxexz ebicc",
        "wzuemcj oyd qupulju iaakzmt vzkvz",
        "nppahov umm wpzev wxkgfxd owgekp bhhb bbhh dgviiw kdfgxwx wryb",
        "bnc rhes lmbuhhy kwbefga bnc rtxnvz bnc",
        "ani mggxf mcoixh zdd nai hbhzl mes bdpqr",
        "mjn uinoty jjegvze bjgqg yhqsxbt coj obylb hddude xqi rhfbhha alood",
        "cbjzj drmihy tfkrhsd nuhav hihzx bvblqpl tdd szmp gjgfv box",
        "uumhdxd cmwgyf vepr rwqdkj exwk",
        "hwvr ydvw bqefu kghes gvbhp awms iqsqes khgse",
        "mrey jqfw fwvzhps komj dayvs fbui zmtd cofn mrey",
        "dsjds fdpx irjj usndok qcctsvf fgk wvg txwxcl dxs llp zyilwtq",
        "xmkelgk fdukc cye legkxkm wwly",
        "enlny eynln cccku brkz dpof mwfoxcd yftmnqh wpebvyc",
        "ggdn jnysl dsacffw ukj hdae cmzxku",
        "uqhm gcachmn kxndfrl htmfis jfnajz fiqiypr kekho kekho ndcw ckrndub dejfna",
        "keazuq ertql rauwl keazuq obmh rauwl ksrotm",
        "jppp poigqhv repfsje grjk xwkyuh pkx ayzcj hoxzv",
        "yhjw pcuyad icie icie icie hwcsuy wcd yihjh jnrxs",
        "gaug ivvx ceb xujonak hbtfkeb ttciml cctoz",
        "dggyyi dggyyi gqlyumf yasu fwdfa cbb nncn verhq",
        "rhgcw gpcyct kiuhbg kiuhbg gpcyct jlmleo nhumm",
        "wulxxu jyjek hclcp ogob viex wiqcupq",
        "tthu nxgzpid kcnj mss ukapgkp nnc bxjocv qwxs oejwsif aywqtu brahkb",
        "dtde bgvb smu vbbg zhlu",
        "lyo nwjjmep ldbok wgxhto wwuh qfgjknk wnsl",
        "lleyr onha hkwulbm jfg",
        "bybjwd uoxvbh mvj iqfpnxs bybjwd zqtszp wvc lbazjr zkzenja cev",
        "rbuyyr divtslq yuqmyt ajyveb smxsjb nlk tzqhq ims fewg wpjhr gqh",
        "kpewfd beq klilis klisli eeezut",
        "euqh hueq ldoo crqurv lvrwh tmaewp oodl",
        "bqi lzrf jyhvxfh bqi jyhvxfh nbztd lwpdn cuzi",
        "srjylou phavzjd wost uxkaq byh sluryoj",
        "ihrdk bcegkpq nygrs qbcq wyjg dvzme pgzhjl vibg kvv",
        "ijsx iedemek ktlz gtga tbal lbki gtga",
        "vmiaxn kefig kefig vngxz",
        "vrdmfvi qts vlvhq vlvhq dihmq",
        "cfz dyrz zlw qnt vok fwvahg skshbqf hbwozdc ntana jdb uflp",
        "rimbj bxemw sfps krtk umta vnk ewmbx nrlje ymrtqrz mxewb kjxunbt",
        "egnuti ozat eltl ngueti",
        "qtcwoxq rmaf qtcwoxq qtcwoxq",
        "zws gcoa pydruw qsrk lrkybdf ugr wkrxoj nyvf vitwn",
        "tmr hhd dojid zwrj bhsim righ keqlep flzunou",
        "lwoquvy acjowxk tqudk oenvioh nyavyl",
        "rgh dfhgyke iff cpxhuz hui koe iff hui dmukrei",
        "bjiumig lcbmbgh vleipx sfawua rnf",
        "gftfh qwb tfdroe xbno qhgofm vqfoe mux",
        "ljdrr gyfggai iun nju xrucbis mhrcrh fukr obvuqc whlalfe xrucbis nju",
        "nxjmjr egqwg arllu xqaahri lzc ivt uhsti",
        "sqiepba rcmts kvesv nvp",
        "tiksw tiksw rjni gbhvzm ctbq zuqfyvz",
        "ibsnm kfka aoqigwo sqouih rxz",
        "jmymq lxio adtmk umyu sxvzquq bporqnb heol fow",
        "mepa eckq rqviawv dkqoei ifmngpp jiava rtklseu",
        "yuycd jiufjci yuycd uowg yuycd udq izkicbr csxobh",
        "nwu tfsjavb rruoxbn oepcov elxf rruoxbn rruoxbn azglwth jcjm ksqiqpv",
        "dthfwip zqnwa zqnwa zqnwa",
        "gso wruece ufl crgnlxv vllsm dpyfm wpa ctxko",
        "wvpze seodz lpq lpq pmtp wsxs ffppx",
        "yfxquj phvjn rtwieq rtwieq kgxztyu vbjvkc prqqd lyzmdo ojbrt ojbrt qiqjz",
        "esaezr rpggiy jey kbzrhu uthus osr xxaiijd qfxlf auhzbx gkigoqw",
        "yfhcj uvgck cds gjhhrg cmempgj yfhcj cjb",
        "yxi voxvtuw unwg jqqm",
        "igvjr ljz rus sru gbjtjt qfeg ztu zjl",
        "leof ocxns hbkoysh hbkoysh leof",
        "hab lyxmf yhh qeks fwhfxki xmbcak okqjii nfgzyg bhtfgdj lpmjn",
        "mgognh tad herere lvwnzx ixwqs zphmuuc etdjz kczsf",
        "mtej rlolsnn zbl uykek dpkan gmz etxtgj",
        "mihuieo emjgbp jgks mihuieo iexrfw mjdnr bvp mcuzea xkbusvi",
        "jvqpj bwt jvqpj bwt gxr",
        "qpnd fpt tpor bibbpcg hmvguez wqc afl ckviua gpi",
        "dntmcg jglm sxtnu sxtnu sxtnu",
        "fzkbptw cbfwo ozvwov wbv gcdd izqo ovwzov lolewo xikqpw",
        "nkxyxzd kpn datf fki werq mwidqx oiibor zizcjph",
        "xvgyxym zor ijoy lvwsf fjuara idvvq rreit mqyyy ctio tzwqqhj rnpee",
        "maqkfpk maqkfpk xukg sfdmnlg xjopvr xjopvr irf",
        "liujcd vnlkouy dxkwc gto vhjvtw",
        "swhqhj cas aupsd swhqhj cas bvbooii jquck dtdm",
        "igh iqicicf ghi pcxt srcrjx gmf gyscphv",
        "drplj drplj wopgpnk wytag wopgpnk",
        "zexe ilcqoh qiefb txkuv lirfzv",
        "ovvpn ovvpn uqeurqx uwzn hgmucj ovvpn sjxulms",
        "rox silka irhsvym kutus otasof tdneav pcagds",
        "mkja omu tyshbfq onp trxs lxa tftbv bnpl djhnc zdqfs muo",
        "tjj rmmqas cbbkxs qio pikk ykyew gxlxt nhsyl ykyew",
        "frcprg njrz oaxcmhc qben pedm ecvtga nzxwpb ior gaklot dpem",
        "zyt kncau spoe qlchg sqys wkpbng yflju qlchg vkve bzadbpa",
        "qtq pkaicl qtq mfkfqvr dnleiq brrjxsx uoyxh pkaicl yvmlug",
        "firwy imtlp ywl qfa dqrbazz ztzb pcsbwhn zesmlag",
        "ivey ivey mtvc mtvc",
        "lhize acwf moa cdeoazd voktshy qmvqq jvmuvk ljfmq tsanygc",
        "xreiqkc aawrovl pofcsg xreiqkc xreiqkc",
        "cjbzvn ozds iniqu sdoz gqmki bablvll krs vjzcbn",
        "izsod htkeqz entxn qtns prpcwu omfnmoy",
        "kwfb tctzda aztctd tadtcz gyt wunbcub ydiwdin xxk",
        "epnl ijcp giq ltfk zjcabve zfksmz epnl giq xxxbsom",
        "ulyukpa mdjsbn dydko uhkdt qms aaaj hustlwu",
        "zlsbu ohx jcwovf egf zlvpqgx qhejm wrywdmw",
        "uhxqrzr mmu kjxcalj unuohiq rri yzngnb ikvlxry mfiym qbksdx",
        "khqciz som yklmm jceb khqciz jspy jceb",
        "ncwggv njvi nqox krtsn lnm",
        "bgtqme xaxcoq qbtgme obqual vorfk baoqul lgrb",
        "jli tsbb nlxjc pkwzmz dlxrj hmho gzguko ilj iyaasm",
        "wlmw grkumg dynwtyo emxhhqr huluk slpqu uhqcmd absmr ufirmwr",
        "pbs pcammxv dplfr tzvmav nccyy blvyq ffhnz bccutq",
        "hgge ghge vxmvz hqxgjdg zab guo gheg",
        "ylj bucoyoq udndc wpgyrbx ueh udndc gxdsdh hdoz wwgqlg",
        "cjdeh gttyqe kdkm ltzd lfeozse quvjq mnwhokm kdv oojxm nxt",
        "mfkzus knqxt saxkqww njx zumsfk sbmcyad cpt agvbuv",
        "tukn vyco yobvsn bzgnn klrnzy kea thzk pxpwq ryfff nxzm",
        "ylbm lxlz lybm lzxl",
        "wgtxoij zad slgsi cvnxfg iomswwl vmx",
        "hkm yinhnkj kmh kwkw kayknck chur styjif yknakck",
        "rtfwhkq rtfwhkq zsf zsf",
        "sldq zlntr ueegiw kajivqc ozcbm ceft snvugom pdyc elppeed nnqrp prwwf",
        "lhk xjonc muc tudag tsafx mmivb dvrjbp qgrew",
        "hnzer fbgqp aazta aazta lxaz lmgv aazta",
        "victgxu victgxu mlpd ummrnbx cazjgnw isxcyp efy zfa cyusj",
        "gyojxo onzq gyojxo uxufp awi ilhl wefwfxr gcjlt tmliynw uxufp pdcnxah",
        "wjwachn xkuhfbp oky oky ybaeqkr rbuix yreoaw wepmye brvon aasb",
        "kiidorw vxtxiqx wtqvbrv efdth isel qbom vcssyc vxtxiqx wtqvbrv riafzsw mqzsj",
        "eurpjd vkhdamt tmfx czeoot hiz ykz lmixzq tfur jhzr",
        "ipuftpj qbll sqkkdw fwncmiv bri oeeh lehd ioh wag",
        "suima nanngc imrmc krq atxdo woy atxdo akev qlr aezco qlr",
        "cfc efwbzck ozkmcxv moczkvx ccf",
        "bnekky iakrk sask uwgnjp iyi rynev bdnas ldh kass",
        "sicmw vvjbvv cap nsumc xgvrlm wsoo uoqdu psykckm",
        "ugg mtr wnzhmmh tjxc ehwnji lwhu mdsckk yvmk enubrqo",
        "grb oxmxz ohu ytetedv ssx apzlppg fdkamm sxofc jdt ynmu wyejok",
        "umoep rbyqm eqfk twqnog cptbbi dragna ngqs ffb cexxnc rbyqm",
        "utizi ormkel wvwur bdx ecelqbv xiccama aag glfvmj",
        "znb rsuqoa uxo svc",
        "obs lbifa cffi catpd",
        "qkxwian ajlzjz wewduzp bbyv qmt fsr qgiu epinp ghmf",
        "hatg bfgmb aght ghat",
        "kuq inp dun cknbun wmwsu drlmmg kyxc bdl",
        "bddybth swdbf jhi fva qpobio bjwm wjaztp jywi",
        "mgckz vhveu zkemhp zdf xtiqqew mlx wazgd",
        "umbjq pya lvvxf jeavij rhrxvew bwjqgpr piz",
        "xaycpwo vjcuc qksc yuixhni sfbfb dydyaq gdfvb tggg xidphvf bpjdrl goskxym",
        "agxfoip gguif wvo agxfoip ntkbaw fbyggy ooft zxih",
        "nzvsu ffwq uxvfbl qrql olhmhom qhdltg ymwz krtndtx olhmhom nfsv krtndtx",
        "qdp jqk ustz xjripzv mnk grnodk pjwdsj uug zqxjqj",
        "mufrcox zunisfs ocvcge acamm xua vor bsde kxr vor kxr orccxx",
        "ncycbp anvcxay bmm wndmeaw oso knmk mmb wamenwd kmkv ppdd",
        "motdcn xzagzwu vuzt utffrn yuqxzrh uvzt ujttq",
        "tauoqy coiy ybesz tauoqy wpmr trquyne ahxbj jzhems dsdy",
        "aczq ypw pgmzz srfn quatjgf",
        "cih ypapk bfxvr euvhkk gugru auhqui",
        "vyf pssgfvy dnhvbfl xpacme dnhvbfl mzdv iynq hcqu",
        "lbzvbu hhxiq hdfyiiz iyzihfd xhqih uzdqyxr",
        "iapbdll vdr cprmrkk vdr dfjqse mlry flpqk vdr",
        "grrfkq xcpxd grrfkq dxc bjpr prvwh swoc swoc",
        "bopo chvwuhf qhd ieesl xey ieesl fnjcbe",
        "kic fyq hsucnu agwyl pzzmd hqksh psw",
        "mxf uau iti lcoz lpg zbu ocre wqlocmh mxf nidqj lcoz",
        "bypmix ptzxgmf xmtzgpf hrvzzq",
        "lbfw zwusma lbfw tuyyy",
        "lrf uej unswvh obgsb npbl zajr kenea uej qnyjcu wzufim qpzkgya",
        "qcrxj llyu kligt hlm ehwtbx dda lgsvhdt xewfcv uikn",
        "nfzjx izqdbq mfbxs imiuc yqxb xlmvix izqdbq eflqfq wku omgtuu izqdbq",
        "lasdwg hiy btzt eefd eyoep icn nnmhg otml rek luixac nyzgn",
        "vekteds utsuxdx utsuxdx vekteds",
        "feyov qrij zbebwg ijrq seplram wttkwm zewbgb kzuhuh",
        "dmkgtv wohgqo ddtqmv zatahx mym hqowog tkmvdg",
        "vhha wjrmuyx kqh vyyrj xzchbi ejsdq orlxg vyyrj dlrc",
        "yetngqn zdtuqox hkarjei fqpsgh eaqwbg zsssog ghb gddqqzr hbg",
        "obldb zsrhz zxp uxphnev mwnbc pfjft fms xwslk vjm fxy",
        "nfij dbfykv ttq gyjgac igxuyqi gtiioqx ilhdex dbfykv uyp bdiwya gqf",
        "pffzruz vogfosh dcs wje",
        "pohhf fhpoh oon yyz",
        "xxuam afwm qxl lnt syyr bwxhhf sozauq shlhfmz kwnn milav ochq",
        "wefcqrt gejw cwerqtf fttf gjew",
        "jfsvnmr osca epwtle pgfif sxom",
        "exlfzmq nakp rgdnx rrcvth vhrrct aajjdrt ryyg dsozd jdqlqj pakn iruv",
        "rmcvo txszcs xxhyxz hbsozk wshkocf rmcvo rcbnt",
        "kitz yjgney yvkymef nauj hmllsgl kyhm kqr pzsu rcf pzsu qpte",
        "cdinpx bfur mkj naz ihkheyr nohhoe",
        "ylris xeqcgup wap bbfih tgfoj",
        "ina gnlnm zyeqhij cudfuf ipufae bvkdzni aat teqsg cudfuf bjokrbl teqsg",
        "aedx edax dnfwq qndwf",
        "rdngdy jde wvgkhto bdvngf mdup eskuvg ezli opibo mppoc mdup zrasc",
        "qcnc iaw grjfsxe gnf gnf",
        "zbjm snznt zelswrk gkhlnx dqxqn qqxnd dmro",
        "zisecvx ztezof uzbq otnrtj qsjzkwm ewvcp rlir bfghlq tgapdr qxmr",
        "ipnqj opjf vabyoe wkwnd",
        "wyf mfqxnrf apm snarf jqu aaghx pwecbv lvghayg",
        "acncv jmmbwlg oiphlm ifuo cvt",
        "pvmb egansnd zmh gcuzzci rrxpslv ubith",
        "uoleptg xbouzn xbmg cfh cpn wpqi xbouzn xtxis sxzpns",
        "rilybri kurbpq vfmjpck tjyogho hfyxad svfofx lfbbhxj khaerfs iqr",
        "seaebgz wlmtkre qguv qguv wlmtkre",
        "sgo edkxya zdqgwtt gxu nibuu rairqoq mzxli dci qsv",
        "tsol mdhzqr rmaqnru ggvcq arbwkn hlkcnj ljkcuof",
        "mmliphp ocup puoc eijjv",
        "gmajqpb ijki ijki kvz",
        "pmqss unhlpcj dlkll nuhlcjp expe tlurzmv nsy vlumtzr tgseozl",
        "gkvaoni hsba hsba viuedv phyoclp fdq phyoclp febld nqfs",
        "rxvdtw abn pntv qrqfzz slsvv abn lrxix mnu npot",
        "ghlfjp woy xwkbmv bkahpkj jve cncvk jvdype fwgvoju yrkwjp gwfvln mvkv",
        "kmluh mie bby fwer chsinb ojglqr nqk mie",
        "yzmiu igkgca ybnsqja jpfejtp yjddy xsosxfi ingx qwuhb emrkwpx idqjmmm",
        "btrllw mphm dkvo ewdl dchcul yah btrllw kmqi mtvgk wtb",
        "hxsgard yuikc lykt tdee adprp gpougod klnzk mzsmlb",
        "hdn znblw ifoblur bwzln dbv",
        "smofpbs vjuyiro llk lfzesga tybu tybu",
        "gffnpug xaup iqiyz fjkpnkz drrk fwyxw lwzfskz gslwpmv vjxylva tbkyo nib",
        "evydmb nhwuiiu fkerq nkgbuyy uclrs ydjgglh xhotwbm riirgzt",
        "bsub eavbt uvd dpzwyt rhn khrbptt xszckc djnfxju axofhat powmso nvdffrv",
        "xtuykl fjz mbikc xpnx hmey fjz fjz",
        "rkls nwdcsyx rkls rkls",
        "tygml untequ ybdfumz nqffbq uipc sove hfnqj",
        "ytecew vven koqn royynd qsn ksl qsn sdw",
        "hknlw qwho whoq oqwh",
        "lzmmtqu qvhyeo cnofuj utpwkjz gnirz yhhu aodbnd",
        "zsr axw kwtzcv tydzo kwtzcv lkxsm",
        "rbjtqe nihifd gvdxd bpxzy rxteky vgcgllv vbbua anygiup rqo",
        "dpd wblfwp wblfwp wblfwp ygahc tqjbaq",
        "gsw gsw pacgj xmrcz zmxhmch xmrcz",
        "pdq rhe xqmq lgpkhg fyffrot ovnqh wle",
        "tbjavke ypzzrj jizx gdxoh icjsat otfh fmygumv",
        "snch nxlgjgp jeyn sxoqfj jtage jtage iuice",
        "rtb coefuj grwg grwg rtb krhqnma vfhgbr",
        "vhegtl btorwxg szcev kbvkx itsk nlzpbed",
        "hiukrf ilzkm yllhh xsgwkdp zyy kjbv",
        "rfcg tdorci zcj wzftlv rfcg rfcg",
        "lgbc lzizat vsno pau nvv vsno bbr lzizat qhtb gwp",
        "sfwnio tcugjk bsfsz ykyfwg ibkap fsrvy mygk kzunawx zyhyh",
        "mpavlh qps bylh lttjkz rqabgk vewb bwev tlzkjt gzrbxga ktmso prpkj",
        "gpf ims ynh ffrs vpa iemp gofh cgbauje",
        "secys qks mcnfhwh drog kqs pajy zoltkw lfihnb myb ioxptu",
        "ytq nrta ouk ajqblf yuwwcd zdy blyoxbw dakk nvgi bzrhzaa",
        "nkoych sufiia xkdvw crtldee zycl qblab egqhr qblab",
        "nllno muxaf vds qjnitmw zkpj wskyhft kmqct xamuzpw qcai cdjtbt kaxv",
        "qzdytpe osr fuw osr qzdytpe whperd rydwdcl knoa",
        "zkdznhd peh duoygr zamrgl irnvj otpe pltpq jdkecg",
        "byzgw rece iigdug ehif tpgje",
        "ccnn foqdran gbctca tefdjxh ntcr rjciii xip xlss crl wvvhzqm twyohf",
        "dqyii milqqc qjgkojp qjgkojp ryde",
        "tdkyj tbrcud tsba vqtmb cjwxnf",
        "hqhmq wemvrce nagig pwnw nagig epg nagig vlsi",
        "tqgvw luoplw hccti npjm rytdruq cylrsun rytdruq vjsbjl rytdruq ppti",
        "itgt tuwc itgt rvp itgt tigns eipl ksmru",
        "pdw wdhtkn nbdbpn wff zhuuipg rvemv qxr",
        "qgkwdq cjilayh ymeks mrpuzai dwgs stfstgz ucvqhb yout oiq",
        "vpxik ypfr qytimvu qms oxbmw ppyfx",
        "fwwidn gdhd pyuexk snsz iwndfw",
        "lfcb sllxjna lfcb hpzahfg mmvgaa svny jhuzd",
        "unyg gicmzd fwc spkciy toyq wjupckd vzzx iuqgka ytqycb pxsufj",
        "goj tnrcml eyizngj txa xrkiw zvu igduz",
        "wek xrrlkna clyof rrlnxak",
        "cjm rmyuku vjom gtf",
        "buk cfae awstd dywgqp hxo wcxvf laihqw xdqfes wdbh qceh uzlwj",
        "sudguo dxwplto rlebdh bkamu dxwplto",
        "crwkyxm yuz kjtdhom crwkyxm",
        "trhc sduorxr aizfryh rsudxor gbyc",
        "pczkyl bptp qnn nxmpwsx udrg hhlb rubtrmx twzodlp xygnht",
        "jmqct cden yfajtkz fevcw sxonbxz sxonbxz qkzkm hhngr fbv",
        "sdsnm mwvicr wypfi cty ndbowr woiz mrauwzd qlno mwvicr",
        "vteyo fng lvr lxytn txpj milg",
        "wjx ahtmgo cgwcaj kaxae fhlvlqf",
        "ezj eetqhzu upwda iiefwlk vyvby",
        "imalvy yeghqe jwcu mvrod cwju",
        "bxnmsa yhfu npsdar tsbri hfuy sirbt oofxmy",
        "fkndt elbjtn vepqtxt elvpf fpelv bzkgag qttexpv prblwb",
        "rmq iqs yvprnyy iezqrzm wlqsrr",
        "yviovq lekxghj oey qwhzj lxknxw qiyovv ksnt jptz",
        "tyrg cifxt hugqf tyrg ffuiv jmax qyw fozfosq ffuiv",
        "nmg rsl jpzazd qbtlf yxqtsj czwmdfd bamge lbjdof uqy jssc",
        "cbx boozjip pwgvzlq rjz kxy kxy hszacok fvsq jhnir cnsba gafz",
        "sbcuxb wfur nnnfqjj fdwg huhe sbcuxb",
        "icwk qelbxs uevp qped zsnhh wpuok wddxsln ftnzupr ruxol cgxjb jbhh",
        "izcp htykj xxmndoq amnspe htykj",
        "vverol oixwlny vqd tvfzu henc gnyrwr",
        "ytxio etytsx choynep zqapo hfjit",
        "lkvgr oyzfa taiqr jok djatvy ckif tmdw oyzfa zroy",
        "jlgpyp kkqysg oqjki hjohoug hbhta muilz zft",
        "sumfyu wftcu bwwdcy lezimwa qwvxv zwh mqyv bmfot aii torcol rnt",
        "tpdj xrw ccsbnh fhptv fwkxjfm dmqaokd bjci",
        "zxi vmf vmf dpyg",
        "sfzxysw lcms bkojtv bkojtv",
        "opywo qll ipkitr mtwp tudrr svhyp huz bxsdpn xomfy",
        "gkod luo qrosbp orbd rpsjzyd rlh gdok tze",
        "nusiuq nusiuq zeys ahufexc",
        "veno jntg avtmtdn qojxru zegdcql odfcetz pgehau",
        "uqun vigjm ykac ozlelj danmji bibugox",
        "rpuozh ajwru rbvuevv uhzsq",
        "iawoe tyb aewio ymf byt inijv ctu fcys micsgzl pbby alt",
        "gktyxp ris mqpfm bkqsfl nrg idbbcxg jhcf",
        "qibt invvv qibt luitx rnm eby hrfbmwl wnap sgkzvb qlwc hrfbmwl",
        "jwkv qecsjbw lycgldd wjvk tjcp dycldgl pzrvr zrlcf kji",
        "nzsrmiq nmhse ilivrk kqv",
        "besmyzi imkgpt iekbjax abxeijk uvzs wwv",
        "jdocl uki ltswp tjkljc ymce iuepze qygqxzs tei lkry",
        "hhyfy gvzd mqksxlq czn afe mesnag eep frwgekg mqksxlq phpy",
        "ehg connnza ekt ddgokw",
        "mpbsoms uzhzl xevww ztt uzhzl",
        "lftybr firc awsud dsxdkk ltf ipjv dtx lcymth",
        "vkcpb gxtxq yioeq fexj xxgqt",
        "srvca fslnnvf nfmkpvt egw wemumq jie vznf dzsjw cukf kcvyir",
        "yxjkl lyjkx jyxlk kgc xtz",
        "tpoe xzov csp leleoqo noyre tdhf cyib sjgtdx raehdw nmcxp",
        "qvt uhznqe bpvos vtq ddlebtd tqv",
        "xlw utsxs gpia rvlvnts elkxr dddihy tnrslvv ibf wlx bxg",
        "cwqnnrt rkkqyf dye yde fzl pthanj",
        "boc rqjenpp xjqte jteqx pvoofc pidqe ruoucy gvnro ognrv",
        "qhalb gnazwc fhl iuti",
        "clnbjfo nnfs nnfs heymvr oarew oarew nxu",
        "lwtrotg hiaxwj ymzbly nvhzjhj zlsaheg nvhzjhj ymzbly",
        "rrvi tsjp tsjp tsjp killji",
        "rpx hiclj cmwq ibhj nfd",
        "pvwymn iebkd xmpw vuhhkap ksw zigzy mzzyyxy rmuh iwwhea cglfq",
        "rlwelgy sffml jin qsdzro xlsty mgqzuu etxjuo emzd jgnoyq tkjuy vfvb",
        "tkctdj hhkuc viskmy obw",
        "zvjkuj akeky ikj jqd hfhzbwe bkc",
        "btev nrdo hcyiuph stf qharfg vpmel mpfz nvs ytgbbc",
        "ieepn ndueuw svmdr tcvumw mceyrn mrjwhyl tbdj mgrgvz",
        "uxrs ckyi xpmqm czzrkl cjp",
        "nlliwd wrqkrkz yjmng nlliwd zirde hcjjn wco ysf mgl",
        "dxti lcahe ommare izlwf ramsfb nzgfvo ijvm fwymrdu bndq",
        "isxy jpvuzu tdduyhw dixp cfa fkzbteg ytoi kepk ysf yqcpi",
        "qmeprfj soqo ncgeor cqsuuj grzy wogxy vyblnbg slvtry vdols kka",
        "ltykfp gtzl olrp gxend vapee deq",
        "emywfbn dbfiut rkt wvwe dbfiut bwffhea yuzcxv gogpicp wvwe",
        "vqvmrp ofbk dlfabd jwllzxk obx vqpwjj umvng tqwis fstxy fstxy",
        "miha zgvyux rmraszo xwf",
        "kjaagk btm kjaagk wkewjrg kjaagk",
        "lbmli aizs omrdr gzktnx asiz ptanzpa xlo ljre ckyb wob",
        "svz dlk rijagg avxmg fkzwhk uro gegm",
        "dzplum temdw jqnm tvxcww bmg tftttpp deuw comxey xfimzjx caluczi nqn",
        "uwvhxa ztkd nlsdyt vihl julkwwv uzch dwakhs",
        "wkhuihh ycrc cxff vzcfhpp uegfd gaok kcnvz lhzogq lwa tyrypvu",
        "idp zmrrzp zmrrzp nktp xsnx rjsxn",
        "eybrnib ivgntl vaxsbpi eybrnib",
        "nzvnq xvbfa pbhwwh ylju runvsj imlx vztesn",
        "nfdohd nfdohd gtevnky pivjyct ihvd fzcsrq lko fmqk",
        "kwpkks ecikxu bcxswlt qvrxm sbcqmh",
        "kdjrmj piuh kdjrmj vnaf gyedkg vptxgm xezssxx zsg qjzpo zsg",
        "oqo sley aqx qmpqb fgmylbj egd zivj kepxizv kuakyn lunbnd",
        "hmcf hmcf xlhgc hmcf cdlm buofnx",
        "onjcj yluonz kzmk phqo phqo phqo",
        "ohaafy efl bnkkjww wwjnyoj dxeaig ywnjjwo slk hrbebw ohlyju elf",
        "msohiqz aunk njki bfktdgi htmyrj mgx",
        "numlzrl rmnlulz glb ltt fhbajz gqxpu",
        "gko hco oai ryq xwy sdqosft spjkiu cxfhg ycwpglh noy rah",
        "btzpjem brpk vqr atxu rhlh rqv jmg fvyus",
        "phmxxgj ejx xje qtk hsb kqt npwj gqt",
        "hujyjp nwmsd ant zipuya lrkahww uwqal vzlo qmbo twkjkse ufivi",
        "zfbnyz fwvh xrnrw usn zin daq iwjzj",
        "yykyg iwypfy hehqnl cjvk cevdrec",
        "gui muuto wsta glqmx gfo rdmbv mxwz gffzt eejpw gion",
        "lpng nduid iqbpu nduid knrqd",
        "xwxn oefpckv gjaua ugaaj gjuaa",
        "qxk aeql trqdmqc crzlinj crzlinj trqdmqc rijcne ewyf",
        "rfv qmbe fvr bmeq",
        "upqyfw lowzq wpen upqyfw gfskbil sljuzh wpen",
        "bdcara qyhx rtaez qyq gbyr",
        "evzls qxtxq clzd svbgqi zxlzgss vtrre fko eebo qjyl",
        "zaapeo kpwhz tygknau nyd pch trp xqe",
        "ypzcafg rnqmbh qtteg sncu ssojhhm zonfym thir xmgheb wqj gpjg ssojhhm",
        "wvcwyn xrf muozyya lasdp xpjgu kpqv zkiihiv ifje cbdlavg xbied hfnaa",
        "qqqb rettz rycukl ihpkhh",
        "dnxzxqv znb znb fbxj azxtezb xvxa",
        "peqkd xlzqkov esgnw ucku hrwpfxd xtd vnig vlmfp ajte qswr kqoj",
        "dpwy oavzkk dwyp ehij upqxgii pydw",
        "amfc hfv xmqa nqvn cal rqmcq oej amqx cla ntxj",
        "hqhhe qkbhwli wmhlcq xaczs peywuo",
        "vcr xfv xfv kymo qpszwzo xfv",
        "nmrbur tswo xbo ljlrzo bmhpgc pev zovkznz lok wbbhtkk",
        "tojj lxqgr rhjavrm ndsdup gdbjwaq cqpnl wfaxivl rfry ryfr udspnd",
        "beffod sknlph amb feobdf",
        "mldgn jxovw yuawcvz kzgzwht rxqhzev fsdnvu vluuo eycoh cugf qjugo",
        "tlnd qcxj ker fdir cgkpo nrqhyq raef uqadf iahy rxx",
        "mhvisju lhmdbs tcxied xeidtc ujry cditex gvqpqm",
        "cgc jazrp crgnna uvuokl uvuokl uoiwl sknmc sknmc",
        "rvbu czwpdit vmlihg spz lfaxxev zslfuto oog dvoksub"]

    end

    def day6 do
        [5,1,10,0,1,7,13,14,3,12,8,10,7,12,0,6]
    end
    
    def day7 do
        [["dihjv (2158) -> gausx, ncdmp, hozgrub"],
["qhvca (428) -> odttvb, ymehff, ymyzbqc, jtdtmsi, wciuyuh"],
["kuvqhnm (77)"],
["eauol (56)"],
["nwtkz (304) -> eykks, rxivjye"],
["kmyvaog (440) -> jrvona, cdoyc, vgbwb, lbttqhl, qizznfs, bftdz, xqhvz"],
["dcqofo (74)"],
["qnhthgm (63)"],
["fgkok (189) -> vjgjzbc, vjfllmr, drbqty"],
["tvfwp (74)"],
["jtwqgg (28)"],
["igogak (57)"],
["edaidjk (60)"],
["jxhqld (75)"],
["jbhxihl (79)"],
["fbrdpr (28)"],
["yjtudlp (60)"],
["wgbdxsx (98)"],
["ecpuvq (84)"],
["emzlv (5)"],
["isahru (26)"],
["oamyk (69)"],
["xxxcdbv (29)"],
["rogwn (357)"],
["jpovtel (31)"],
["gkvko (24)"],
["aqlfh (87)"],
["cbvzgp (24) -> weotr, pgofcu, czswzal"],
["vaqxfkm (43)"],
["fwraw (64)"],
["rqtlp (13) -> tmoib, pidha, yaqiuq, zprfu, ssjau, duhaz, qzaecfk"],
["qisdg (15)"],
["oryhdxc (12)"],
["lywem (78)"],
["ulrqrc (38)"],
["sszuwps (86)"],
["qanswmb (89)"],
["keubv (101) -> yhfkwn, toqhzbx, rokeyia, vpspcd"],
["lkpdlq (36)"],
["ddvbfi (75)"],
["nsfjyfr (79) -> pavvcsj, thidj, yvjkb, udkcxo, zehou"],
["yorihlo (5983) -> eihhef, iayesbs, nduld, darnez"],
["xfkhu (208) -> izjecb, edqurgi"],
["onnmq (24)"],
["zmbxthx (2453) -> tfjhcnn, uifjku, kgtcv"],
["turomx (35)"],
["pgofcu (82)"],
["yveziks (55)"],
["cbmcpho (20)"],
["cosmq (70)"],
["xvnqny (3179) -> dpmqmbp, pddgbo, mszglrh"],
["juqsjg (47)"],
["zfhup (56)"],
["agvvr (45)"],
["pkdqgo (84)"],
["yupciox (47)"],
["wplhnmi (689) -> qnmiv, esemf, qiftt"],
["qujsvg (58)"],
["bdnqwvw (10384) -> mqyvpvw, kfaib, rpgxh, kjudskk, gknpczm, mtukvee, xwbzev"],
["lfjwzpr (80)"],
["rpdiks (56)"],
["kveyw (87)"],
["eiwvcil (276) -> kmquncz, bsqltzs"],
["lflpbjx (28)"],
["nnoiyn (218) -> qthns, nhpvo"],
["togvh (177) -> qcsal, totymbv, wdrdfsy"],
["fmpkks (88) -> kbseli, tukvj, hygejev"],
["hoocyf (77)"],
["bbhffib (11) -> orrno, uaeuig, yjicxmr, yhmqg"],
["bjaferd (58)"],
["pjsevmq (112) -> sxnfkj, jyaztbk"],
["zsksm (26) -> nghpciz, pboxau, nykhzm, edteba, bbhffib"],
["mngpa (189) -> wevea, cjkpmpb"],
["clqlpi (96) -> jgvmp, ikfnuu, dqfeapy"],
["uppsb (10)"],
["thafg (61)"],
["dgmbzo (157) -> sjitmwi, krmoek"],
["xtcoefd (13)"],
["vnlbdhq (75)"],
["rfowcu (46)"],
["znpcapb (13)"],
["gnrgy (839) -> zuqew, prnpyu, payeaey, mxiqn, qmkod, rgovzj"],
["glmvo (1473) -> slilxt, fikmr"],
["kiwzzsi (26)"],
["lqrleq (114) -> xljwrd, lrymzqx, kszzcjg, ajxjsi"],
["xdvxnd (82) -> alxuwj, ynfamq, oymcuyi, iesan, urqvtwz"],
["oyort (96)"],
["nmzkhig (11) -> jponcak, vyyvfme, amzzkz"],
["cwgspa (10)"],
["fahjx (47)"],
["hckss (31)"],
["eflhrzc (210) -> jnswdp, hrhky"],
["gzgmcg (53)"],
["ctvqg (32)"],
["hmaslr (146) -> bvyiw, qeeyslp"],
["xsxpz (46)"],
["ztdib (46)"],
["xhsokp (60)"],
["gtadjbm (86)"],
["qrrzkla (54)"],
["zsmex (16)"],
["wmiuyq (55)"],
["mqovh (297)"],
["tfejm (26)"],
["hozgrub (96)"],
["plgyftr (130) -> daomuol, lynvr"],
["fjbxbui (57)"],
["rnxpn (84)"],
["jrrcr (22)"],
["dxujggm (73)"],
["gnows (81)"],
["ilziw (54)"],
["drbqty (15)"],
["bgfjxde (292) -> cwgspa, uppsb"],
["omcvezl (74)"],
["cejrzz (88)"],
["zbrant (83)"],
["rxnyoaf (59)"],
["vbobjo (98)"],
["ofydl (110) -> ssmijv, uxytt"],
["uwweklj (20)"],
["iodjrt (60)"],
["wdaxi (67) -> jxhqld, xxtds, udeyv"],
["jivcmug (241)"],
["rgovzj (147) -> cdmqq, iwvgsqj"],
["gsspm (506) -> wakslhh, wjjov, fwjvl"],
["cssxuh (85)"],
["bdbhdz (22)"],
["kjsimg (45)"],
["mfaiso (99)"],
["pzgihig (152) -> lggutbs, qrrzkla"],
["xzrts (87)"],
["alxuwj (241) -> sguelmy, wwibd"],
["socdh (28)"],
["tnezwo (65)"],
["tonetb (74)"],
["budlgt (226) -> edmdyyf, oulbft"],
["wgkylta (318) -> tozgnf, nybvxpl"],
["sddte (99) -> ywgsoss, pjgpn, unzqb"],
["ijlnjse (45)"],
["knkect (83)"],
["nftvm (40) -> hepgwl, xsnvuhk, awuntf"],
["nhpvo (56)"],
["khfehu (76)"],
["slnoou (74)"],
["qkmsfo (220)"],
["wciuyuh (184) -> waand, zutluof"],
["prnpyu (29) -> pkdqgo, gprqd"],
["illog (99)"],
["pxijfx (35)"],
["alcjel (83)"],
["owjae (264) -> jxawhq, mgxmj"],
["xsjmrv (178) -> husfjac, zsmex"],
["kgjnta (24)"],
["bfmatc (6)"],
["whnmg (1178) -> fajwz, fjbxbui"],
["ulsjdhh (44)"],
["todve (10)"],
["mgomqm (35)"],
["okvspp (63)"],
["kgtcv (41) -> mhbvu, wycrhq"],
["vzyknp (26)"],
["agmrdd (49)"],
["ilqgy (57)"],
["lhomu (99)"],
["ixknb (57)"],
["gffatn (656) -> rogwn, ralyx, xhnem"],
["rbgidcj (1416) -> bgczgya, xgbxcgw, shzcz, qonlajs, naxbp"],
["ikamn (24)"],
["qzaecfk (253) -> ctvqg, yunmx"],
["gknpczm (155) -> eiukshg, bomwsw, zsuhred"],
["kulazu (78)"],
["jgvmp (78)"],
["wxhex (24)"],
["tvdihgf (85)"],
["xwbzev (254)"],
["ankqb (83)"],
["zehou (270)"],
["yehoudc (237) -> tdvdbhx, rlzldzq, cchwxl"],
["gvktxip (74)"],
["kwbbdg (9)"],
["fnuem (788) -> sgxaa, wkqbmut, wkqtgn"],
["xljwrd (20)"],
["xsnvuhk (90) -> ibjay, tonetb, uowuztv, hdvwu"],
["pidha (77) -> iodjrt, wltkgyg, nipcsis, yjtudlp"],
["gausx (96)"],
["cbtfaaq (140) -> ochqzjy, oogoc"],
["onurc (93)"],
["oahfm (823) -> gxzkef, zujfczp, tmakc"],
["jujcekp (87)"],
["ochqzjy (32)"],
["wvihi (36) -> rhdngzm, udeckgc, aooskui"],
["eosnpun (42)"],
["vnivx (24)"],
["iziyeah (53)"],
["wrrjvv (138) -> kktnr, nduasyx"],
["rncwlve (45)"],
["ohvsnc (16)"],
["kuwksy (81)"],
["epmklw (24)"],
["bnhmicm (49)"],
["kamhkoi (154) -> bndye, wjxgvh"],
["sqvgekz (156) -> ogelzn, smueqkc"],
["fikmr (87)"],
["nipcsis (60)"],
["fevoc (49)"],
["itihxls (53)"],
["hygejev (63)"],
["xuwzr (289)"],
["zzbpjiq (80)"],
["aakqco (77)"],
["mhtrp (80)"],
["ftwjsi (5)"],
["slilxt (87)"],
["bgqxrj (98)"],
["gpaljor (160) -> kuzskeg, qloih"],
["vmrfkpj (97)"],
["extedk (63)"],
["wlswfp (38)"],
["fphae (82) -> yhjmn, ylkotm, zmfcp"],
["jlxseu (12)"],
["waaszgs (95)"],
["cdoyc (208) -> ikamn, ywfwlug"],
["xqlcwdq (82)"],
["iqsxq (61)"],
["iegfxt (84)"],
["lnbkylg (58)"],
["qcsal (55)"],
["onyvo (98)"],
["hrfldlv (61)"],
["pqccx (49)"],
["zkpvqfo (24)"],
["svpplpy (364) -> znpcapb, ervfo"],
["ksbkavj (145) -> cypwd, rxnlgc"],
["ucuojn (95)"],
["fmszt (23)"],
["sqoqld (5)"],
["ymtwg (89) -> oqhdqg, qwfzkh, qrbhvs, phkvd, ytkgrpj, ylfkshq, drwjl"],
["nxwsaq (59)"],
["skcbz (98)"],
["ygnrm (40)"],
["asfjop (15)"],
["doqmfx (152) -> ahsdq, gnows"],
["jfrda (3994) -> lnpuarm, oahfm, nsfjyfr"],
["kssoys (63)"],
["syqthpz (70) -> zyfrk, nhlvwm, lfjwzpr, zzbpjiq"],
["pxbyvn (98)"],
["goulcd (164) -> wdngppj, vmrfkpj"],
["keeet (281) -> wdpyn, hqyej"],
["pscda (342)"],
["edqurgi (91)"],
["phkvd (37) -> vmbhr, zppzac, euaulyx, cabffwx"],
["cpvefk (15)"],
["jyyeena (51)"],
["naxbp (17) -> ofgvb, ytvmvhy"],
["cabffwx (71)"],
["pvnch (61)"],
["omvoojd (20)"],
["edteba (305) -> qjdbq, yupciox"],
["gkmrz (29)"],
["qwfzkh (321)"],
["eatpn (88)"],
["ptfev (215) -> iemffhw, snzqh"],
["kuzskeg (30)"],
["acvbzia (390)"],
["zbuqlk (52)"],
["icbztci (67)"],
["awebzjn (46)"],
["hxwrnx (7)"],
["yvjkb (9) -> pttqho, jujcekp, sabsqv"],
["qdrqm (182) -> cssxuh, lpfrtfw"],
["pynygd (99)"],
["tthcan (67)"],
["vzlomr (127) -> rztel, fscztrk"],
["hljxim (70)"],
["wputsbp (91) -> zdrfc, iqsxq"],
["qsqxc (69)"],
["jzztae (158) -> wqrxb, yjqyh"],
["qloih (30)"],
["nsmsgmk (93)"],
["awuntf (276) -> kunyye, yveziks"],
["ibjay (74)"],
["ssszfaj (24)"],
["wildi (97)"],
["kunyye (55)"],
["hvporje (17) -> xfuimef, pscda, pklufv, vejgx, togvh"],
["ekcfvm (58)"],
["wkqtgn (96) -> brqztvl, rbjzgxt, jciigs"],
["dqfeapy (78)"],
["gsjkku (24)"],
["uxytt (92)"],
["qnrlrm (57)"],
["gvtcjha (98)"],
["kygnpb (75)"],
["yjqyh (78)"],
["pixawh (64)"],
["xwwdp (53)"],
["yjijem (124) -> jyyeena, frpagb"],
["uihqn (52)"],
["hdvwu (74)"],
["sijptix (87) -> ojatorf, wxlxyq, lkfttr, xfesea, ytatg, keeet, ghycpf"],
["nzylp (26)"],
["zcoqx (164) -> xxykvzq, slnoou"],
["vlrgx (88) -> bmntp, eatpn, yvoyt"],
["hqwqd (97)"],
["ybsouxh (24)"],
["wurmarr (46)"],
["bmejz (97)"],
["rfmtzl (9)"],
["lclhy (36)"],
["qyharq (92)"],
["ixtmdxo (24)"],
["nlrtoa (57)"],
["bnqinhv (440) -> hgwpks, wputsbp, mngpa, dasoy"],
["gndaa (12)"],
["syzkg (1697) -> qzdatks, buekex"],
["wevea (12)"],
["bcefufj (22)"],
["larhlj (152) -> tidour, qfxuh"],
["npvrbd (896) -> fmpkks, vpmnutl, uvsgv"],
["pjgpn (65)"],
["mzjypeq (90) -> ihhmv, jckrdlz, kylpt"],
["lfkfd (97)"],
["wysgri (142) -> gnutx, vbqxz"],
["zqhans (87)"],
["lqsdtq (43)"],
["zutluof (6)"],
["wqxbp (34139) -> bdnqwvw, bdlqru, ysgrizu"],
["mrdoeb (87)"],
["xuprtp (93)"],
["vgbwb (130) -> wesqml, ssinas"],
["zoibb (46) -> ctosb, pskrkrn"],
["qmoxv (42)"],
["bdfns (29)"],
["qqokzne (954) -> jscxo, fhcrsce, jscvn, amheqov, wvihi, wsxkjcu"],
["mxiqn (107) -> kjsimg, agvvr"],
["klyfish (1069) -> xxeoneh, kibotum, hmaslr, zuywf"],
["lzjvenf (21) -> tjfib, jgjgxgb, ibyqrv"],
["yeomv (42)"],
["qdyjn (78)"],
["kdvzyz (6)"],
["ncdmp (96)"],
["hdkeesr (56)"],
["dcbquim (48)"],
["ksjmqsc (529) -> oakpkr, ndsbbnm, fphae, extnd"],
["sczsl (64)"],
["akvfgdi (57)"],
["njldiph (83)"],
["dasoy (155) -> qppyecj, gkmrz"],
["jlhdq (52)"],
["ltwrzdl (16)"],
["fenxwbi (42)"],
["vhnpij (78)"],
["frpagb (51)"],
["hqxulc (5)"],
["tretx (11)"],
["jorvuw (83)"],
["vwyrjd (31)"],
["zpanms (59)"],
["qjdbq (47)"],
["qagqi (83) -> xqlcwdq, ezbdihm"],
["nydgtu (73)"],
["bndye (39)"],
["wlnpbx (83)"],
["vbqxz (85)"],
["levsigy (43)"],
["cdmqq (25)"],
["ekrwiea (91)"],
["rxnlgc (14)"],
["mtflqcm (68)"],
["kylpt (72)"],
["arwyg (238) -> ngsgolg, qephec"],
["gprqd (84)"],
["qawlwzi (45782) -> jfrda, jwebvqn, ujwqlf"],
["qjqqkjo (300) -> vwyrjd, ocddu"],
["azjdyr (89)"],
["xjgoko (622) -> larhlj, lrvaz, memnafg"],
["thidj (116) -> xzllgwq, vcfxh"],
["sguelmy (36)"],
["tjfib (59)"],
["rdnxsro (84)"],
["sdvzbk (262) -> atvztnt, zkpvqfo, gavzpv, rjmjlq"],
["ssvcrjn (26)"],
["rilzcsz (186) -> epmklw, sczuqy"],
["hkosdxh (79)"],
["iodtwit (30)"],
["lvlux (92)"],
["udkcxo (84) -> xuprtp, simsfkz"],
["acatw (69) -> tlpzsi, hakss, naiivve, pphbkn"],
["tflqwyl (51)"],
["zjlckg (9455) -> jvjdgph, sijptix, zmbxthx"],
["adqqjrz (81) -> ebjind, odhurs"],
["yceabkj (46)"],
["tomfuoi (6)"],
["vejgx (272) -> lzvpll, pxijfx"],
["qmpazxn (37)"],
["pskrkrn (90)"],
["eigivg (43)"],
["cvioak (68) -> qnhthgm, wboesxc"],
["dwfxj (76)"],
["kjudskk (206) -> vostn, ixtmdxo"],
["xltuf (66)"],
["rnjyw (55)"],
["uowuztv (74)"],
["zkmhy (220) -> rnjyw, tbswgx"],
["cfxrv (83)"],
["hrbse (124) -> lnwyra, xuzfgha"],
["urqvtwz (81) -> qcayjn, lnbkylg, yfrcx, bjaferd"],
["lzvpll (35)"],
["dngizd (81)"],
["sjitmwi (55)"],
["tqruh (31)"],
["tukvj (63)"],
["mvncpt (21)"],
["hzfarz (51)"],
["ujqoks (20)"],
["wezrgqw (210)"],
["hopsivz (387) -> tufywu, zhmevu"],
["cacfqur (9)"],
["udeckgc (59)"],
["lkimdg (10)"],
["nulkw (61)"],
["porcbbb (227) -> midrlp, cacfqur"],
["lmjpuv (296) -> kxaxt, fahjx"],
["wimpns (22)"],
["oymcuyi (280) -> tretx, njarebf, svezft"],
["qfxuh (20)"],
["fxjkoqn (202) -> fwraw, pixawh"],
["vcfxh (77)"],
["jtdtmsi (90) -> gzgmcg, nrkdwvs"],
["vkuusw (92)"],
["apjkf (22)"],
["ovdogi (165) -> shepkcs, npxgl, wxyrdp"],
["ewbuve (88)"],
["dqxfl (90)"],
["xnmtop (83) -> ckugbl, yeomv, fyktlox"],
["piewts (22)"],
["gcvxpm (64) -> kveyw, kchjfpg, mrdoeb"],
["tufywu (32)"],
["xfesea (243) -> tthcan, wljomq"],
["ysyfwqs (211)"],
["ozdrm (76) -> lclhy, zggsrug, zvhtk, lkpdlq"],
["oqhdqg (201) -> dunqe, fqhdf, ygnrm"],
["gmmxg (29)"],
["rokeyia (27)"],
["gavzpv (24)"],
["mifxlz (171) -> didfetj, rncwlve"],
["cqjoftq (63)"],
["fhcrsce (213)"],
["ssjau (253) -> askmldt, kojat"],
["wdsunq (58)"],
["tcqkzp (208) -> udzokmu, lzlvrqk"],
["eimcci (43)"],
["xwxof (55)"],
["spprj (68) -> jorvuw, cfxrv"],
["ivkvrj (81)"],
["xbabgu (155) -> lypml, zxvhoy"],
["osnyi (50)"],
["cdynw (89)"],
["ldswpyl (30) -> jkjnsj, lpxekhm"],
["rdbcued (24)"],
["zunuwi (208) -> iziyeah, wdafwyi"],
["pzjiiy (20)"],
["xqhvz (192) -> liearc, ohvsnc, ltwrzdl, ypyuum"],
["vtzay (74) -> vonbixj, qawlwzi, wqxbp, tcsrpxb, xlieqz, yghqsa, asexwc"],
["ralyx (357)"],
["rlpvqn (9)"],
["yjngab (1573) -> yiigm, kntzn, rilzcsz, eqoick"],
["vtnex (28)"],
["ctosb (90)"],
["zmicnlj (76)"],
["hbcjzma (149) -> bbmvgyu, rxnyoaf"],
["lmekort (6)"],
["jkjnsj (87)"],
["pyjymxj (59)"],
["pjczjl (20)"],
["wxmwf (29)"],
["othvtfq (49)"],
["atvztnt (24)"],
["ehzatio (57)"],
["ekdczsz (63)"],
["njarebf (11)"],
["qsjhc (59)"],
["ridrtgx (9)"],
["kamrqhv (57)"],
["wgjbas (15)"],
["ldtbli (78)"],
["cniapi (15)"],
["ulssbyo (62)"],
["ashohg (12)"],
["mtkliz (96) -> bxkicdp, pmlzll, ycqghs"],
["extnd (178) -> piewts, rpiyqq, bdbhdz"],
["wvdnc (77)"],
["iyalpvz (13) -> uohcpp, xcyfp, ypbgol"],
["smkeec (87)"],
["ezbdihm (82)"],
["amheqov (177) -> isnebf, rlpvqn, bllths, rfmtzl"],
["bmqggm (108) -> hkamx, extedk"],
["ajnnoo (99) -> ywpmdg, drsvx"],
["wgwucvi (26)"],
["xbwbjfa (46)"],
["omlxdye (56) -> tdstj, gnktgh"],
["esbswlu (246) -> kuvqhnm, aakqco"],
["wljomq (67)"],
["yowef (55) -> umhji, ucpgr, dpimy, nwxad"],
["qzdatks (15)"],
["ncuksjv (84) -> plcqel, mtflqcm"],
["mrssfl (26)"],
["uqjnlv (122) -> rqtgag, awebzjn, wurmarr, osbdc"],
["xxykvzq (74)"],
["ynfamq (187) -> fenxwbi, eosnpun, kybtr"],
["jscxo (99) -> dathq, ixknb"],
["ohpeic (695) -> cbvzgp, mjrxbh, aaibd"],
["bnuozu (107) -> rstvy, kovebn, zwsjm"],
["kxaxt (47)"],
["rztel (62)"],
["xubkl (102) -> bhzgqav, wftxaby"],
["owsebz (26)"],
["glqezpx (245) -> omvoojd, pzjiiy, oiuppwr"],
["ssmijv (92)"],
["mgdjgzf (573) -> fnsxlna, qjqqkjo, pgfhmr, tvtxqpd"],
["rnzzm (246) -> uwweklj, ujqoks, cbmcpho"],
["npxgl (13)"],
["lzlvrqk (42)"],
["xgbxcgw (97) -> ashohg, gndaa"],
["ibffwi (21) -> zfxdqi, yxqmz, dvnvwgj, xnhlg"],
["wzmrtpw (40)"],
["lcggft (139) -> qzuyecq, sslulx"],
["vlwmaxi (46)"],
["fnsxlna (110) -> cqjoftq, kssoys, fwyreea, wkgzwhi"],
["zlwnppb (491) -> uqjnlv, huidcr, rnzzm, mzjypeq, inycp"],
["jyaztbk (61)"],
["ipljy (79)"],
["wdpyn (48)"],
["pgfhmr (50) -> kulazu, lgmdhjw, qdyjn, lywem"],
["vjgjzbc (15)"],
["egtscru (9)"],
["plcqel (68)"],
["wbsul (175) -> ynqji, qcbubp"],
["fajwz (57)"],
["bftdz (24) -> fdpjo, ekcfvm, qujsvg, wdsunq"],
["wkhsng (24)"],
["nhrka (23)"],
["njkscdv (10)"],
["vihoep (161) -> qolkd, itihxls"],
["wesqml (63)"],
["xgsbu (19)"],
["iayesbs (2129) -> zhzwir, zoibb, kyvysg"],
["noutnp (202) -> kdvzyz, tomfuoi, bfmatc, lmekort"],
["whnnb (66) -> yceabkj, vlwmaxi, xsxpz"],
["ucpgr (38)"],
["qzuyecq (34)"],
["nwxad (38)"],
["ljmkw (53) -> imdmnn, hkosdxh"],
["vakhjoj (1289) -> reflh, himyfxm, hrbse"],
["mwzhn (75)"],
["otzqal (667) -> qagqi, vpdlxtj, fiilaqx"],
["kktnr (30)"],
["tmoib (303) -> hxwrnx, ukbfn"],
["bkuqfi (8) -> gvtcjha, pxbyvn, miwvcdi, wgbdxsx"],
["ifroqmy (4870) -> ksjmqsc, ohpeic, djomjuh"],
["ghycpf (199) -> azjdyr, qanswmb"],
["fecze (694) -> jzztae, doqmfx, givqy, zfrgif, budlgt, zunuwi"],
["derxp (22)"],
["siyudl (46)"],
["eqcpltg (79)"],
["sslulx (34)"],
["ibvmb (49) -> njldiph, zerai, ankqb"],
["lbnjp (122) -> ojcaeht, sszuwps"],
["vwzfjcq (241)"],
["ytatg (116) -> mldtcbl, jgsgm, aqlfh"],
["tdvdbhx (19)"],
["bomwsw (33)"],
["aonteu (15)"],
["ndsbbnm (76) -> mxdij, nmqoxw, eauol"],
["rpgxh (140) -> eetdzon, igogak"],
["ynqji (40)"],
["obhlzp (56)"],
["jscvn (169) -> twdnswr, bcefufj"],
["empkyy (61)"],
["peopfnu (17) -> etyhx, rpfhcus, yvyttr"],
["wycrhq (25)"],
["isnebf (9)"],
["naiivve (43)"],
["cchwxl (19)"],
["swtbqxz (266)"],
["hbcto (51)"],
["husfjac (16)"],
["uohcpp (63)"],
["yozose (88)"],
["ylfkshq (193) -> sczsl, ibdyuge"],
["ergcql (46)"],
["ebjind (65)"],
["tohprmh (2242) -> tflqwyl, mdjhnv, tamautu, qxxkyr"],
["bqbmy (49)"],
["urbqmk (52)"],
["zdrfc (61)"],
["wwibd (36)"],
["lawgz (35)"],
["lkfttr (320) -> luzwzm, mqebpw, eodubb"],
["ezxlkm (37)"],
["eihhef (1752) -> adqqjrz, ysyfwqs, ljmkw, synynkd, imrqsxa"],
["nduld (1449) -> lgkhn, cikijr, ijmrhsf, cvioak, lqrleq, ifncxs, bnuozu"],
["cdsjzoz (1888) -> yowef, wdsari, lcggft"],
["djxpma (93)"],
["rstvy (29)"],
["yvyttr (1210) -> qslmjtg, wrmovs, ibvmb, xmfrzwa"],
["vnhsudk (60)"],
["qrshe (43)"],
["flovshu (15)"],
["bwgjpdg (97)"],
["bgczgya (107) -> cvgdzag, qdextxi"],
["zfrgif (168) -> dxujggm, nydgtu"],
["vpdlxtj (151) -> wxhex, gsjkku, wkhsng, ssszfaj"],
["kwztfbl (88)"],
["nduasyx (30)"],
["jnswdp (60)"],
["rbjzgxt (24)"],
["cvgdzag (7)"],
["cbxomli (91)"],
["qmkod (57) -> hlauw, mgomqm, pmzvdb, lawgz"],
["weotr (82)"],
["ifncxs (54) -> fglgibd, hljxim"],
["ogelzn (35)"],
["pkdwpbh (15)"],
["mdjhnv (31) -> njkscdv, hincte"],
["hxxupnf (43) -> cjztdo, uvgvi"],
["imrqsxa (115) -> drwlyvx, ybsouxh, xfmyvg, oibng"],
["gnutx (85)"],
["iloykn (81)"],
["heudq (6)"],
["lggutbs (54)"],
["bllths (9)"],
["edmdyyf (44)"],
["wrmovs (132) -> alcjel, knkect"],
["nfwzt (69)"],
["esemf (99) -> iqeqpuv, seruan"],
["omspdwl (245) -> ggmpihl, emzlv, kjyhry"],
["uillw (1744) -> zfswb, wbsul, dumykdj"],
["ijmrhsf (102) -> ztdib, rfowcu"],
["xgllgu (62) -> illog, mfaiso"],
["ofgvb (52)"],
["fscztrk (62)"],
["iwfjou (31)"],
["egqaydx (814) -> ofydl, sddte, nqpyzt, yehoudc, szpoqm, lbnjp"],
["vvemxld (63) -> xoavai, subauko"],
["jkukq (9)"],
["tmakc (44) -> tqxmke, ipljy"],
["veefoj (99)"],
["cmopifq (234) -> zpanms, nxwsaq"],
["jkzwu (70) -> zhphopf, pcljlai, uillw, qamvl, cdsjzoz, yjngab, vqhriyt"],
["xkrxt (81)"],
["fgltnc (22)"],
["wdrbtqg (8) -> wezrgqw, eubxp, wmmmcdw, eealm, xsjmrv"],
["wspzdb (60)"],
["wzcttac (85)"],
["wqlzmvc (87)"],
["ervfo (13)"],
["bxkicdp (57)"],
["seruan (12)"],
["wqocyox (99)"],
["wdafwyi (53)"],
["drsvx (71)"],
["yntroh (82) -> rvakt, hoocyf, fgrvof, ccjmduk"],
["uaeuig (97)"],
["wspnoa (291) -> hqvtn, iodtwit"],
["bhzgqav (18)"],
["ycpxqjz (55)"],
["szpoqm (98) -> qqedfa, qeovb, agmrdd, othvtfq"],
["zxvhoy (85)"],
["waand (6)"],
["brqztvl (24)"],
["jatwhbu (93)"],
["tbswgx (55)"],
["nghpciz (205) -> lfkfd, hqwqd"],
["oulbft (44)"],
["pcljlai (949) -> fxmiw, gmawv, pzgihig, ipqct, xgllgu, omspdwl"],
["ggmpihl (5)"],
["qonlajs (73) -> smuzxf, trxfjv"],
["twijj (54) -> qrmgjdu, avyif, veefoj"],
["owiryv (54)"],
["yhfkwn (27)"],
["eprlek (42)"],
["xlieqz (18992) -> byytwu, yorihlo, vrpupk"],
["geznv (32) -> tvdihgf, fccyl"],
["smueqkc (35)"],
["wdngppj (97)"],
["vzits (78)"],
["bdavc (79)"],
["luzwzm (19)"],
["lrvaz (96) -> qflimon, dcbquim"],
["bvyiw (46)"],
["esvca (90)"],
["nylrq (400)"],
["tezto (34)"],
["qqedfa (49)"],
["nulkvu (29)"],
["xuzfgha (60)"],
["vsivyn (38)"],
["qzhemjq (91) -> cejrzz, yozose"],
["bmntp (88)"],
["pwotv (26)"],
["vonbixj (42470) -> orssb, ewqui, ifroqmy"],
["eleeg (82)"],
["ylpapdi (15)"],
["dpmqmbp (292) -> cmopifq, vlrgx, qdrqm"],
["ciiqis (295) -> cqxfbv, socdh"],
["lnwyra (60)"],
["vyyvfme (35) -> jqomxi, hwljl, onyvo, bvykqm"],
["jxawhq (47)"],
["kntzn (78) -> vhnpij, tqnucz"],
["fvbopgf (302) -> bnhmicm, pqccx"],
["mgxmj (47)"],
["dodbb (53)"],
["smlvcc (1242) -> lzjvenf, plgyftr, wrrjvv, dlrpc, nevkxz"],
["amzzkz (323) -> kiwzzsi, wgwucvi, mdyce, pwotv"],
["jzmezwj (40)"],
["yjicxmr (97)"],
["ssinas (63)"],
["ojcaeht (86)"],
["tfjhcnn (91)"],
["udeyv (75)"],
["rlxoojp (446) -> cbtfaaq, whnnb, srbtea"],
["ymehff (28) -> iegfxt, rdnxsro"],
["wxyrdp (13)"],
["hbncq (91) -> hwvxsq, dqxfl, hhoxisa, fuorh"],
["drlkvy (190) -> nixbq, fqcxo, itggp, egtscru"],
["scmwcz (20)"],
["lpxekhm (87)"],
["nevkxz (138) -> flovshu, iivqj, clikxp, wgjbas"],
["mqyvpvw (254)"],
["tdstj (88)"],
["lyfyg (1272) -> whzdf, qlgbx, pfzcu, swtbqxz"],
["bdejd (93)"],
["tamautu (15) -> jlxseu, oryhdxc, fbedmnf"],
["wdrdfsy (55)"],
["bvtwq (47)"],
["kjyhry (5)"],
["unzqb (65)"],
["jofsg (64) -> mwzhn, oumcdij, vnlbdhq"],
["ouadkun (43)"],
["byytwu (89) -> tohprmh, timjt, ncapjgu, yblxjc, wmhkk, dihjv, yxjeaj"],
["wsxkjcu (97) -> pdkxh, ahklb, bdfns, xxxcdbv"],
["ywthj (79)"],
["ehofuzh (26)"],
["ywpmdg (71)"],
["duhaz (93) -> rpdiks, zfhup, hdkeesr, zsrdtht"],
["mzozh (77) -> hiiqxv, qnrlrm, ehzatio, nlrtoa"],
["hzuprgn (665) -> xnmtop, keubv, yhkrp"],
["ltwvide (890) -> ajnnoo, acatw, qeyzth, jivcmug, aqzbepp, vwzfjcq"],
["hkamx (63)"],
["nrkdwvs (53)"],
["cjkpmpb (12)"],
["ojnmrwc (213) -> xbwbjfa, ergcql"],
["hrhky (60)"],
["xoavai (55)"],
["totymbv (55)"],
["aqzbepp (49) -> peaud, oyort"],
["zsuhred (33)"],
["aooskui (59)"],
["shepkcs (13)"],
["qggwp (87)"],
["tidour (20)"],
["avyif (99)"],
["pdkxh (29)"],
["kybtr (42)"],
["qizznfs (100) -> vykcb, ldtbli"],
["ykxrxbb (19)"],
["liearc (16)"],
["atkpc (43)"],
["oumcdij (75)"],
["knfad (87)"],
["hincte (10)"],
["nfwof (32)"],
["oxwbxc (10)"],
["bgnuk (65)"],
["iivqj (15)"],
["rlzldzq (19)"],
["qolkd (53)"],
["yxhfz (38)"],
["qeeyslp (46)"],
["qrmgjdu (99)"],
["vbtznz (6) -> vovinsx, vkzka, adkvr"],
["etcbg (54) -> eigivg, atkpc, tyzcg, jlhnkk"],
["adkvr (97)"],
["miwvcdi (98)"],
["jwiwydu (667) -> ihgiq, hxxupnf, hlgydhq"],
["kmquncz (57)"],
["vrpupk (9477) -> kktud, egqaydx, fecze"],
["kekabeg (17)"],
["bovla (327) -> arbcqfz, mvncpt, xhypb"],
["omfahxa (99)"],
["gvwkbp (300) -> wxmwf, qiwsut"],
["twgdnl (74)"],
["dumykdj (71) -> lvlux, rebxtnk"],
["zvhtk (36)"],
["pmlzll (57)"],
["fccyl (85)"],
["zfxdqi (76)"],
["fdpjo (58)"],
["lpfrtfw (85)"],
["tcsrpxb (48956) -> peopfnu, rajmc, xvnqny"],
["svezft (11)"],
["vqcjj (22)"],
["nqpyzt (294)"],
["subvci (97)"],
["askmldt (32)"],
["qeyzth (143) -> vlgwzi, bqbmy"],
["zxqrm (232) -> fevoc, kritjfi"],
["umhji (38)"],
["xifubdw (15)"],
["snxbszd (20)"],
["pfzcu (266)"],
["zhphopf (52) -> wspnoa, kaxrm, vmobtbb, ciiqis, threc, ysvmncq, twijj"],
["ysvmncq (173) -> cdynw, kzchhz"],
["paofxz (140) -> hckss, jpovtel"],
["qflimon (48)"],
["vovinsx (97)"],
["qchmzht (79)"],
["wkgzwhi (63)"],
["wxlxyq (272) -> turomx, zpekki, rfbnete"],
["drwlyvx (24)"],
["kfaib (206) -> rdbcued, kgjnta"],
["baovbha (65)"],
["odhurs (65)"],
["rpiyqq (22)"],
["twdnswr (22)"],
["ypbgol (63)"],
["xhpzhpq (292)"],
["ywgsoss (65)"],
["yrepvc (34)"],
["ocddu (31)"],
["zfswb (155) -> osnyi, ofrfo"],
["sxnfkj (61)"],
["tvtxqpd (322) -> lkimdg, yqmse, todve, oxwbxc"],
["qephec (76)"],
["swhlcvm (47)"],
["ahklb (29)"],
["ydibgyz (27)"],
["himyfxm (37) -> qsqxc, retzg, nfwzt"],
["lcfycgg (1529) -> lhomu, omfahxa"],
["zqozw (59)"],
["hwljl (98)"],
["zvlftj (53)"],
["inycp (78) -> dwfxj, rnyyal, ilcoe"],
["lynvr (34)"],
["hhjspt (241) -> jtwqgg, bdjgtz, bynxcni"],
["gkvojlo (87)"],
["xzllgwq (77)"],
["pboxau (399)"],
["oazcn (45)"],
["buekex (15)"],
["odttvb (162) -> kekabeg, momoy"],
["rfedd (74)"],
["ymyzbqc (144) -> vzyknp, mrssfl"],
["ftfvpmy (193) -> klmcwy, xltuf"],
["utqtp (87) -> zqhans, knfad"],
["ktnynk (23)"],
["jlhnkk (43)"],
["jponcak (339) -> ytgxvzv, derxp, cukeme, vqcjj"],
["subauko (55)"],
["bgkst (257) -> pjczjl, scmwcz"],
["uifjku (91)"],
["ujwqlf (46) -> xdvxnd, sbjvkrb, glilvcd, glmvo, eiennk"],
["vjfllmr (15)"],
["nhlvwm (80)"],
["dpslcf (82)"],
["tqnucz (78)"],
["yhmqg (97)"],
["bqqwwcn (1031) -> kamhkoi, omlxdye, ismqdcu"],
["ismqdcu (178) -> lfrwzbb, ydibgyz"],
["rebxtnk (92)"],
["lcpfw (296) -> vrjes, bvtwq"],
["drwjl (265) -> vtnex, qxzjhg"],
["nykhzm (11) -> bmejz, wildi, qoyub, epdfbvu"],
["rvakt (77)"],
["hakss (43)"],
["noqrlh (60)"],
["epdfbvu (97)"],
["iqeqpuv (12)"],
["ywfwlug (24)"],
["weywe (57)"],
["kchjfpg (87)"],
["fbedmnf (12)"],
["uvsgv (237) -> eyotuoe, slhfj"],
["fqcxo (9)"],
["vsfjq (56)"],
["whumv (84)"],
["sczuqy (24)"],
["hqyej (48)"],
["fglidf (9)"],
["yfrcx (58)"],
["ytvmvhy (52)"],
["vykcb (78)"],
["cukeme (22)"],
["pqiqied (93)"],
["cikijr (32) -> xkrxt, zspsh"],
["mtukvee (59) -> baovbha, tnezwo, bgnuk"],
["vlgwzi (49)"],
["wdsari (41) -> wlnpbx, zbrant"],
["shzcz (52) -> ztlsw, ktnynk, fmszt"],
["kaxrm (261) -> oazcn, ijlnjse"],
["eubxp (81) -> vaqxfkm, levsigy, lqsdtq"],
["vmobtbb (237) -> kamrqhv, weywe"],
["zzacgi (90)"],
["oogoc (32)"],
["dlrpc (40) -> jbhxihl, kdjcqk"],
["eealm (88) -> nulkw, pvnch"],
["jciigs (24)"],
["fpezemw (67)"],
["lgkhn (134) -> wzzjnrl, snxbszd, vexft"],
["ldyrkdm (40)"],
["zezecwh (53)"],
["pavvcsj (218) -> ssvcrjn, nzylp"],
["kwelmvo (46) -> siyudl, wxiks"],
["mszglrh (472) -> tcqkzp, xhpzhpq, wdaxi"],
["fmsgmoq (135) -> xgsbu, ykxrxbb"],
["ahsdq (81)"],
["lypml (85)"],
["simsfkz (93)"],
["bdjgtz (28)"],
["aaibd (174) -> vnivx, fcjoefo, gkvko, onnmq"],
["mgihcl (354) -> gwcwh, nhrka"],
["udzokmu (42)"],
["qactli (85)"],
["eqoick (176) -> nulkvu, gmmxg"],
["synynkd (167) -> jrrcr, apjkf"],
["darnez (77) -> syqthpz, lmjpuv, lcpfw, bovla, wgkylta, xfkhu, acvbzia"],
["vrjes (47)"],
["zemwgsa (130) -> isahru, cltdxy, tfejm, obzcog"],
["hlauw (35)"],
["pttqho (87)"],
["zhmevu (32)"],
["mhbvu (25)"],
["autys (32)"],
["qeovb (49)"],
["brhvbt (93)"],
["jrkohk (98)"],
["yiigm (122) -> qqwda, vsfjq"],
["gdfxr (1002) -> jrkohk, bgqxrj"],
["yqmse (10)"],
["bdbzuf (539) -> ztpizq, gbyiobd, vzlomr"],
["toqhzbx (27)"],
["obzcog (26)"],
["whzdf (140) -> vznyiu, eprlek, iovtj"],
["yytai (13)"],
["nwsjspa (18) -> noqrlh, edaidjk"],
["djomjuh (20) -> bgkst, skrnzrc, mqovh, vbtznz, druym"],
["pklufv (152) -> ucuojn, waaszgs"],
["vmbhr (71)"],
["jrvona (88) -> mowgm, whumv"],
["hepgwl (226) -> ufjxj, mhtrp"],
["oakpkr (132) -> obhlzp, qijjq"],
["wopxs (74)"],
["wltkgyg (60)"],
["gnktgh (88)"],
["yhjmn (54)"],
["klmcwy (66)"],
["bbmvgyu (59)"],
["eifws (205) -> bfvol, qmoxv"],
["xinyjeu (44)"],
["bfvol (42)"],
["mowgm (84)"],
["orssb (41) -> lyfyg, ymtwg, ltwvide, zuccp"],
["lnpuarm (918) -> ksbkavj, fmsgmoq, biumgl"],
["bvykqm (98)"],
["xnhlg (76)"],
["mxwdp (81)"],
["jowykql (63)"],
["atnmou (54)"],
["bdlqru (3118) -> gsspm, bdbzuf, whnmg, bnqinhv, hzuprgn, fnuem, nmzkhig"],
["ddcgqm (10) -> smkeec, wqlzmvc, tcifkj, xzrts"],
["gjkplw (85)"],
["gsbypm (52) -> msnnza, drlkvy, etcbg, sqvgekz, noutnp, yjijem"],
["jwebvqn (7762) -> iwudd, fvwwm, vvemxld"],
["eiennk (912) -> porcbbb, bqdtmvh, txoqtpz"],
["mqebpw (19)"],
["ztpizq (65) -> qwwur, xdwcgk, ulssbyo"],
["dunqe (40)"],
["ccjmduk (77)"],
["kzchhz (89)"],
["wkqbmut (34) -> icbztci, fpezemw"],
["txoqtpz (49) -> vbobjo, skcbz"],
["vpmnutl (232) -> cniapi, xifubdw, asfjop"],
["asexwc (93) -> tmclxe, aiuyg, jkzwu, zjlckg"],
["yvoyt (88)"],
["midrlp (9)"],
["qlgbx (98) -> ecpuvq, rnxpn"],
["bvczy (60)"],
["qnmiv (79) -> gxvlomg, wimpns"],
["qthns (56)"],
["kibotum (68) -> gjkplw, wzcttac"],
["nixbq (9)"],
["ckugbl (42)"],
["iveta (147) -> ywthj, oqahna"],
["rnyyal (76)"],
["vostn (24)"],
["fcjoefo (24)"],
["ibyqrv (59)"],
["tcifkj (87)"],
["jgjgxgb (59)"],
["yduyn (40)"],
["jnurmw (860) -> xuwzr, eifws, jofsg"],
["wboesxc (63)"],
["ibdyuge (64)"],
["ypyuum (16)"],
["yxjeaj (1226) -> mzozh, iveta, ojnmrwc, glqezpx"],
["kyvysg (158) -> yrepvc, tezto"],
["clikxp (15)"],
["ojatorf (98) -> nsmsgmk, djxpma, onurc"],
["eetdzon (57)"],
["pqzsukm (40)"],
["fgrvof (77)"],
["iovtj (42)"],
["zsrdtht (56)"],
["wnvzf (37)"],
["czswzal (82)"],
["zmfcp (54)"],
["hgwpks (213)"],
["bqdtmvh (141) -> jlhdq, zbuqlk"],
["qiftt (78) -> pkdwpbh, qisdg, cpvefk"],
["vqhriyt (1903) -> paofxz, iyalpvz, geznv"],
["udptfka (79) -> brhvbt, bdejd, pqiqied, jatwhbu"],
["yxqmz (76)"],
["zerai (83)"],
["kmpjivb (175) -> hrfldlv, empkyy, thafg"],
["kktud (72) -> sdvzbk, ddcgqm, goulcd, kmpjivb, awqjs, owjae, gvwkbp"],
["lrymzqx (20)"],
["fiilaqx (247)"],
["aiuyg (12841) -> xjgoko, gdfxr, nftvm, jwiwydu"],
["kojat (32)"],
["wmmmcdw (36) -> gkvojlo, qggwp"],
["gwcwh (23)"],
["eykks (13)"],
["qwwur (62)"],
["hodlob (312)"],
["iwudd (85) -> ulsjdhh, xinyjeu"],
["wxiks (46)"],
["zuccp (1166) -> zemwgsa, pjsevmq, bmqggm, spprj, fgkok"],
["qppyecj (29)"],
["uvgvi (67)"],
["upmft (70)"],
["ncmenyx (74)"],
["vznyiu (42)"],
["oiuppwr (20)"],
["zujfczp (122) -> yduyn, ldyrkdm"],
["sabsqv (87)"],
["tmclxe (8705) -> rqtlp, kmyvaog, qqokzne, smlvcc"],
["hqvtn (30)"],
["qcayjn (58)"],
["vexft (20)"],
["ihgiq (39) -> oamyk, fhyimvw"],
["qxxkyr (25) -> qmzef, xtcoefd"],
["ycqghs (57)"],
["rajmc (1933) -> rlxoojp, vtgfsqt, wdrbtqg, leytj, wplhnmi"],
["iesan (151) -> owiryv, ilziw, atnmou"],
["qslmjtg (283) -> hqxulc, ftwjsi, sqoqld"],
["rxivjye (13)"],
["qqwda (56)"],
["hhoxisa (90)"],
["yblxjc (2420) -> viqnxm, yytai"],
["rhdngzm (59)"],
["tlpzsi (43)"],
["glilvcd (423) -> bzsupo, ptynfu, ldswpyl, pwaypt, ovdogi, vomul"],
["ptynfu (110) -> swhlcvm, juqsjg"],
["qrbhvs (285) -> ridrtgx, kwbbdg, fglidf, jkukq"],
["hlgydhq (15) -> mxwdp, pwwtnz"],
["ilcoe (76)"],
["imdmnn (79)"],
["gxvlomg (22)"],
["djsyo (43)"],
["bzsupo (32) -> gtadjbm, hmsbly"],
["rjmjlq (24)"],
["yhkrp (165) -> fgltnc, kfqykbd"],
["kszzcjg (20)"],
["gxzkef (116) -> qrshe, djsyo"],
["jvjdgph (1373) -> hopsivz, hbncq, udptfka"],
["wjxgvh (39)"],
["ysgrizu (73) -> jnurmw, hvporje, syzkg, lcfycgg, bqqwwcn, gffatn, npvrbd"],
["jqomxi (98)"],
["vpspcd (27)"],
["rpfhcus (452) -> svpplpy, arwyg, nlzfsx, yntroh, eiwvcil"],
["eodubb (19)"],
["givqy (18) -> tvfwp, rfedd, wopxs, omcvezl"],
["kafnt (15)"],
["ytgxvzv (22)"],
["eyotuoe (20)"],
["zyfrk (80)"],
["bynxcni (28)"],
["kfqykbd (22)"],
["pphbkn (43)"],
["biumgl (97) -> ulrqrc, wlswfp"],
["viqnxm (13)"],
["hwvxsq (90)"],
["pwaypt (102) -> hzfarz, hbcto"],
["lbttqhl (130) -> ekdczsz, jowykql"],
["hmsbly (86)"],
["ewqui (3753) -> gsbypm, enurd, otzqal, qhvca"],
["krmoek (55)"],
["mldtcbl (87)"],
["sezloa (63)"],
["zggsrug (36)"],
["daomuol (34)"],
["nlzfsx (240) -> kygnpb, ddvbfi"],
["cltdxy (26)"],
["oqahna (79)"],
["orrno (97)"],
["fhyimvw (69)"],
["tqxmke (79)"],
["mdyce (26)"],
["zprfu (317)"],
["ytkgrpj (265) -> lflpbjx, fbrdpr"],
["iwvgsqj (25)"],
["yghqsa (56478) -> vakhjoj, klyfish, rbgidcj, zsksm, mgdjgzf, gnrgy, zlwnppb"],
["nedixbk (6)"],
["kbseli (63)"],
["zppzac (71)"],
["sgxaa (64) -> urbqmk, uihqn"],
["pddgbo (13) -> hbcjzma, vihoep, mtkliz, qzhemjq, dgmbzo"],
["memnafg (15) -> zqozw, pyjymxj, qsjhc"],
["mxdij (56)"],
["qxzjhg (28)"],
["xhnem (93) -> wrnejq, ewbuve, kwztfbl"],
["oibng (24)"],
["fxmiw (248) -> heudq, nedixbk"],
["qamvl (949) -> wysgri, wfuwg, bgfjxde, zcoqx, hodlob"],
["cuwpd (77)"],
["itggp (9)"],
["fvwwm (121) -> ehofuzh, owsebz"],
["qijjq (56)"],
["bsqltzs (57)"],
["trxfjv (24)"],
["zuqew (135) -> iwfjou, tqruh"],
["wfuwg (57) -> yscbbtq, qactli, znxntbo"],
["srbtea (204)"],
["cqxfbv (28)"],
["ufjxj (80)"],
["wmhkk (2150) -> gvktxip, ncmenyx, dcqofo, twgdnl"],
["ipqct (108) -> khfehu, zmicnlj"],
["fwjvl (82) -> zzacgi, esvca"],
["didfetj (45)"],
["pmzvdb (35)"],
["izjecb (91)"],
["ztlsw (23)"],
["lgmdhjw (78)"],
["momoy (17)"],
["payeaey (197)"],
["etyhx (92) -> nwtkz, zkmhy, fxjkoqn, zxqrm, eflhrzc, clqlpi, nnoiyn"],
["xcyfp (63)"],
["xxtds (75)"],
["gmawv (104) -> vzits, gvlbzp"],
["qmzef (13)"],
["skrnzrc (103) -> bwgjpdg, subvci"],
["wrnejq (88)"],
["ajxjsi (20)"],
["tyzcg (43)"],
["zuywf (118) -> pqzsukm, wzmrtpw, jzmezwj"],
["huidcr (66) -> vnhsudk, wspzdb, bvczy, xhsokp"],
["vtgfsqt (275) -> ptfev, mifxlz, utqtp"],
["wftxaby (18)"],
["snzqh (23)"],
["ylkotm (54)"],
["smuzxf (24)"],
["wqrxb (78)"],
["nmqoxw (56)"],
["lfrwzbb (27)"],
["hiiqxv (57)"],
["wakslhh (156) -> xwwdp, dodbb"],
["xdwcgk (62)"],
["jgsgm (87)"],
["fuorh (90)"],
["reflh (180) -> nfwof, autys"],
["mjrxbh (194) -> vsivyn, yxhfz"],
["xfmyvg (24)"],
["vomul (6) -> wqocyox, pynygd"],
["qoyub (97)"],
["tozgnf (36)"],
["pwwtnz (81)"],
["sbjvkrb (22) -> gcvxpm, ftfvpmy, xbabgu, ibffwi, hhjspt"],
["druym (60) -> eqcpltg, qchmzht, bdavc"],
["fyktlox (42)"],
["kritjfi (49)"],
["xmfrzwa (187) -> ezxlkm, wnvzf, qmpazxn"],
["dvnvwgj (76)"],
["euaulyx (71)"],
["rqtgag (46)"],
["threc (211) -> cosmq, upmft"],
["dathq (57)"],
["jckrdlz (72)"],
["osbdc (46)"],
["leytj (506) -> ngppbum, kwelmvo, nwsjspa, xubkl"],
["fglgibd (70)"],
["yscbbtq (85)"],
["cjztdo (67)"],
["slhfj (20)"],
["enurd (528) -> gpaljor, ncuksjv, ozdrm, qkmsfo"],
["yunmx (32)"],
["awqjs (204) -> cuwpd, wvdnc"],
["arbcqfz (21)"],
["qdextxi (7)"],
["rfbnete (35)"],
["wzzjnrl (20)"],
["xxeoneh (54) -> vkuusw, qyharq"],
["kovebn (29)"],
["kdjcqk (79)"],
["zpekki (35)"],
["zwsjm (29)"],
["ofrfo (50)"],
["fqhdf (40)"],
["iemffhw (23)"],
["timjt (2360) -> ouadkun, eimcci"],
["nybvxpl (36)"],
["ukbfn (7)"],
["ngsgolg (76)"],
["peaud (96)"],
["ldyke (294) -> zezecwh, zvlftj"],
["qcbubp (40)"],
["gbyiobd (87) -> dpslcf, eleeg"],
["wjjov (97) -> wmiuyq, xwxof, ycpxqjz"],
["xhypb (21)"],
["ncapjgu (46) -> esbswlu, bkuqfi, nylrq, fvbopgf, mgihcl, ldyke"],
["ngppbum (12) -> okvspp, sezloa"],
["dpimy (38)"],
["fwyreea (63)"],
["vkzka (97)"],
["zhzwir (112) -> akvfgdi, ilqgy"],
["znxntbo (85)"],
["xfuimef (18) -> kuwksy, ivkvrj, dngizd, iloykn"],
["msnnza (44) -> cbxomli, ekrwiea"],
["retzg (69)"],
["qiwsut (29)"],
["eiukshg (33)"],
["ikfnuu (78)"],
["zspsh (81)"],
["gvlbzp (78)"],
["yaqiuq (272) -> aonteu, kafnt, ylpapdi"],
["cypwd (14)"],
["ihhmv (72)"]]
    end
end